name: ptyhon testing pipeline

on: 
 push: 
  branches:
    - main

jobs:
  testing_code:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code 
        uses: actions/checkout@v2

      - name: setup ptyhon
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - name: install dependancies
        uses: pip install -r requirements.
        
      - name: run test cases
        run: pytest --cov=calc --cov-report=term